workflows:
  dev:
    name: Dev Pipeline
    instance_type: mac_mini_m2
    max_build_duration: 120
    working_directory: new_app_two
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "."
    when:
      changeset:
        includes:
          - "android/**"
          - "shared/**"
          - "build.gradle.kts"
          - "settings.gradle.kts"
          - "gradle/**"
        excludes:
          - "ios/**"
    scripts:
      - name: Build Dev APK For
        script:
          flutter build apk --debug
          # CURRENT_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "com.solo.flutter_codemagic_app" --tracks="internal")
          # echo "versionCode=$((CURRENT_BUILD_NUMBER + 1))" > "$CM_BUILD_DIR/version.properties"
          # flutter build appbundle --release --build-number=$(($CURRENT_BUILD_NUMBER + 1))
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
