workflows:
  dev:
    name: Dev Pipeline
    instance_type: mac_mini_m2
    max_build_duration: 120
    working_directory: new_app_one
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    when:
      changeset:
        includes:
          - "android/**"
          - "shared/**"
          - "build.gradle.kts"
          - "settings.gradle.kts"
          - "gradle/**"
        excludes:
          - "ios/**"
    scripts:
      - name: Build Dev APK
        script: flutter build apk --debug
      - name: Build Dev IPA
        script: flutter build ios --simulator
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/iphonesimulator/Runner.app
